#pragma once
#include "CoreMinimal.h"
#include "EPartyError.generated.h"

UENUM()
enum class EPartyError {
    None,
    CreatePartyFail,
    CreatePartyFail_PlayerAlreadyInParty,
    ConnectionToPartyManagementLost,
    AcceptInvitationFail,
    AcceptInvitationFail_InvitationExpired,
    AcceptInvitationFail_PartyIsFull,
    AcceptInvitationFail_PartyDoesNotExists,
    AcceptInvitationFail_VersionMismatch,
    AcceptInvitationFail_StreamingInstallationIncomplete,
    AcceptInvitationFail_PartyAlreadyInMatchmaking,
    AcceptInvitationFail_AllPartyMembersAreInMatch,
    RejectInvitationFail,
    RejectInvitationFail_PartyDoesNotExists,
    InvitationFail,
    InvitationFail_PartyDoesNotExists,
    InvitationFail_PlayerAlreadyInParty,
    InvitationFail_NotFriendsWithUser,
    JoinRequestFail,
    JoinRequestFail_PartyDoesNotExists,
    JoinRequestFail_PlayerAlreadyInPartyOrPartyFull,
    JoinRequestFail_BannedFromParty,
    JoinRequestFail_FriendNotInParty,
    JoinRequestFail_PartyIsPrivate,
    JoinRequestAcceptedFail,
    JoinRequestAcceptedFail_PartyDoesNotExists,
    AcceptJoinRequestFail,
    AcceptJoinRequestFail_RequestNotFound,
    AcceptJoinRequestFail_PartyDoesNotExists,
    RejectJoinRequestFail,
    RejectJoinRequestFail_RequestNotFound,
    RejectJoinRequestFail_PartyDoesNotExists,
    CancelJoinRequestFail,
    CancelJoinRequestFail_RequestNotFound,
    RealTimeMessagingDisconnected,
    FriendBlocked_UnableToJoinParty,
    FriendBlocked_UnableToRemainInParty,
    CancelInvitationFail,
    CancelInvitationFail_PartyDoesNotExists,
    SendPartyChatMessageFail,
    SendPartyChatMessageFail_PartyDoesNotExists,
    SendPartyChatMessageFail_MessageNotAllowed,
    InvitationValidationError,
    InvitationValidationError_StandardInviteFlowButActiveCrowdPlay,
    InvitationValidationError_QueueToPlayInviteButInactiveCrowdPlay,
    InvitationValidationError_PartyIsFull,
    InvitationValidationError_PartyDoesNotExists,
    InvitationValidationError_VersionMismatch,
    InvitationValidationError_StreamingInstallationIncomplete,
    InvitationValidationError_FriendBlocked,
    InvitationValidationError_InsufficientPrivileges,
    InvitationValidationError_PlayerBanned,
    InvitationValidationError_LocalCrossplayIncompatibility,
    InvitationValidationError_RemoteCrossplayIncompatibility,
    InvitationValidationError_ListenServerCrossplayIncompatibility,
    RemovePlayerFromPartyFail,
    JoinFail_PlayerAlreadyInParty,
    UnknownError,
};

