#pragma once
#include "CoreMinimal.h"
#include "EEmblemProgressionType.generated.h"

UENUM(BlueprintType)
enum class EEmblemProgressionType : uint8 {
    SurvivorLightbringerStartingValue,
    SurvivorLightbringerGeneratorRepair,
    SurvivorLightbringerTotemCleanse,
    SurvivorLightbringerKillerDiversion,
    SurvivorLightbringerExitGameOpen,
    SurvivorUnbrokenTimeAlive,
    SurvivorBenevolentStartingValue,
    SurvivorBenevolentHealing,
    SurvivorBenevolentHooked,
    SurvivorBenevolentUnhook,
    SurvivorBenevolentPerformUnhook,
    SurvivorBenevolentSaveFromKiller,
    SurvivorBenevolentUnsafeUnhook,
    SurvivorBenevolentHitWhileCarrying,
    SurvivorEvaderStartingValue,
    SurvivorEvaderSneaking,
    SurvivorEvaderChaseWon,
    SurvivorEvaderChaseLost,
    SurvivorEvaderPalletStun,
    KillerGatekeeperStartingValue,
    KillerGatekeeperGeneratorDefense,
    KillerGatekeeperGatesClosed,
    KillerDevoutStartingValue,
    KillerDevoutSacrifice,
    KillerDevoutDisconnect,
    KillerDevoutMoris,
    KillerDevoutAllSurvivorsHooked,
    KillerDevoutHooksBonus,
    KillerMaliciousStartingValue,
    KillerMaliciousInjuries,
    KillerMaliciousHookStages,
    KillerMaliciousInjuriesHealed,
    KillerMaliciousEscapeGrasp,
    KillerMaliciousDisconnect,
    KillerChaserStartingValue,
    KillerChaserSurvivorFound,
    KillerChaserSurvivorLost,
    KillerChaserHit,
    KillerChaserChaseWon,
    KillerChaserProximityToHookPenalty,
    Invalid,
};

