#pragma once
#include "CoreMinimal.h"
#include "EInputInteractionType.generated.h"

UENUM(BlueprintType)
enum class EInputInteractionType : uint8 {
    VE_None,
    VE_Interact,
    VE_AttackInteract,
    VE_ItemInteract,
    VE_Rush,
    VE_Run,
    VE_ItemUse,
    VE_ItemDrop,
    VE_InteractMash,
    VE_LeftRightMash,
    VE_ExternalRequestDrop,
    VE_ExternalRequestFlashlightStunUncloak,
    VE_ExternalRequestPalletStun,
    VE_ExternalRequestStunUncloak,
    VE_ExternalRequestPalletStunUncloak,
    VE_ExternalRequestStun,
    VE_ExternalRequestDropByStunning,
    VE_ExternalRequestDropByStunningByPallet,
    VE_ExternalRequestDropByWiggleFree,
    VE_ExternalRequestDropBySkillCheck,
    VE_ExternalRequestKillerCaughtInBearTrap,
    VE_ExternalRequestDestroyWithPowerAttack,
    VE_ExternalRequestHarpoonRifleStun,
    VE_ExternalRequestGeneratorTrapStun,
    VE_FastInteract,
    VE_ExternalRequestSlashedOutOfTrap,
    VE_ExternalRequestSacrifice,
    VE_Gesture01,
    VE_Gesture02,
    VE_Gesture03,
    VE_Gesture04,
    VE_ExternalChainBlink,
    VE_ExternalRequestStunEvilWithin,
    VE_ExternalRequestKickStun,
    VE_ExternalRequestEscape,
    VE_Struggle,
    VE_Action,
    VE_ExternalRequestPutToSleepStun,
    VE_Crouch,
    VE_ExternalRequestRBTExecute,
    VE_ActionKiller,
    VE_ExternalRequestRBTExecuteAtExit,
    VE_ExternalRequestStunBySkillCheck,
    VE_AbilityUse,
    VE_ExternalRequestClosetStun,
    VE_ExternalRequestClosetExitFast,
    VE_ActivatablePerk01,
    VE_ActivatablePerk02,
    VE_ActivatablePerk03,
    VE_ActivatablePerk04,
    VE_CancelCharge,
    VE_WiggleLeft,
    VE_WiggleRight,
    VE_SecondaryAction,
    VE_Count,
    VE_MAX UMETA(Hidden),
};

