#pragma once
#include "CoreMinimal.h"
#include "ELoadProgress.generated.h"

UENUM()
enum class ELoadProgress {
    NotStarted,
    Init,
    ArtificialDelay,
    DisconnectingPresencePlugin,
    ValidateOnlineSubsystem,
    CheckingPlatformService,
    PreMirrorsLogin,
    ConnectingToMirrors,
    StartEAC,
    LoadingAuthInfo,
    LoadingBackendConfigs,
    SetupRichPresence,
    LoadingBackendTunables,
    ApplyingCDNPatch,
    AquiringExternalAuthentication,
    LoadingPlayerIndependentShopData,
    LicenseCache,
    LoadingEvents,
    LoadingInventory,
    SyncingOwnedCharacters,
    LoadingProfile,
    LoadingMirrorCurrencies,
    LoadingWallet,
    LoadingConsent,
    LoadingGameConfigs,
    LoadingCharacterXPTables,
    CheckingPendingTransactions,
    LoadingContentSchedule,
    LoadingNews,
    SendingAnalytics,
    ValidateData,
    ValidatingClientVersion,
    CheckingNeedForCurrencyMigration,
    MigratingCurrenciesToMirror,
    SyncingFriendsList,
    Complete,
    Locating,
    InitializingRTMConnection,
    LoadingStreamVideoData,
    CollectingFreeCatalogItems,
    DownloadDynamicContent,
    CheckingMobilePendingTransactions,
    LoadMarketingBanners,
    LoadingSubscriptionStatus,
    RequestingTrackingAuthorization,
    LoadingExperimentalFeatures,
};

