#pragma once
#include "CoreMinimal.h"
#include "SettingsId.generated.h"

UENUM()
enum class SettingsId {
    None = -0x1,
    Language,
    RevokeConsent,
    BhvrAccount,
    AllowCrossplayGeneric,
    AllowCrossplayLive,
    AutoDeclineFriendRequests,
    PlayerId,
    PartyPrivacy,
    Quality,
    AutoAdjust,
    Resolution,
    FullScreen,
    MenuScaleFactor,
    HudScaleFactor,
    SkillCheckScaleFactor,
    LargeText,
    HUDPlayerNamesVisibility,
    HUDKillerHookCountVisibility,
    HUDScoreEventsVisibility,
    MainVolume,
    MenuMusicVolume,
    Headphones,
    MuteOnFocusLost,
    InvertYAxis,
    SurvivorMouseSensitivity,
    SurvivorControllerSensitivity,
    KillerMouseSensitivity,
    KillerControllerSensitivity,
    SurvivorToggleInteractions,
    KillerToggleInteractions,
    SprintToCancel,
    ColorBarPalette,
    ColorBlindMode,
    ColorBlindModeIntensity,
    BeginnerMode,
    Subtitles,
    SubtitlesBackgroundOpacity,
    SubtitlesSize,
    SurvivorCameraSensitivity,
    KillerCameraSensitivity,
    MenuMusicVolumeOn,
    MainVolumeOn,
    AimAssist,
    SurvivorQuickTurn,
    KillerQuickTurn,
    FPSLimit,
    AutoQuality,
    ControlType,
    CustomizedControls,
    DynamicResolution,
    InvertYAxisSurvivor,
    BetaWiggleSkillCheck,
};

