#pragma once
#include "CoreMinimal.h"
#include "EHudComponent.generated.h"

UENUM()
enum class EHudComponent : uint8 {
    ACTION_PROMPT,
    ACTION_PROGRESS_BAR,
    GENERATOR_ICON,
    HATCH_ICON,
    EXIT_ICON,
    LOCAL_PLAYER_STATUS,
    OTHER_PLAYER_STATUSES,
    SURVIVOR_HOOK_COUNT,
    CROUCH_BUTTON,
    CENTER_INTERACT_BUTTON,
    DIRECTIONAL_STICK,
    WIGGLE_BUTTONS,
    STRUGGLE_BUTTONS,
    POWER_BUTTON,
    ATTACK_BUTTON,
    OBJECTIVES,
    LOUD_NOISE_INDICATOR,
    SECOND_ABILITY_BUTTON,
    ACTION_BUTTON,
    CANCEL_BUTTON,
    DROP_SURVIVOR_BUTTON,
    LOOK_BACK_BUTTON,
    CENTER_ITEM_CONTAINER,
    MOVEMENT_LOCK,
};

