#include "StartLitActivationTimerRemainingCooldownElapsedIconStrategy.h"

UStartLitActivationTimerRemainingCooldownElapsedIconStrategy::UStartLitActivationTimerRemainingCooldownElapsedIconStrategy() {
}

