#include "GenerateStoreCustomizationExclusionFileCommandlet_KrakenCatalog.h"

UGenerateStoreCustomizationExclusionFileCommandlet_KrakenCatalog::UGenerateStoreCustomizationExclusionFileCommandlet_KrakenCatalog() {
}

